### PR TITLE
Clarify prefetch expectations and documentation

### LINKED ISSUE #5: Clearly define prefetching expectations
Our documentation needs to clearly define the prefetching expectations of both the EHR and CDS Service. Ultimately, the question that needs to be answered is:

_When a CDS Service requested prefetched data, is this a hint to the EHR or a requirement?_

If prefetching is a requirement, should the EHR communicate to the CDS Service that it cannot fulfill the prefetch request?

Is it OK if the EHR can prefetch some of the requested data but not all?

Also see the past discussion over on this [defunct issue](https://github.com/cds-hooks/cds-hooks/issues/9).

### PR DESCRIPTION
**Pull request by isaacvetter**
pre-fetch is a request, not a requirement and can be partially fulfilled.

Requested prefetch information may not always be supplied to the service
and may be partially supplied -- in which case, the CDS service should
query the EHR's FHIR service for the missing data.

The EHR will not expose internal errors to the FHIR server.

Fixes #5

### CODE REVIEW

**Comment by kpshek** [comment]
@isaacvetter, @mattberther, and @brynrhodes --

I wanted to add even further clarifications and details to our prefetch documentation to make it even more explicit. Rather than asking for @isaacvetter to make further changes, I thought it'd be easier to propose some additions myself. I've updated this PR with those changes in d2157a5. Please re-review these changes.

Isaac - since you're the author on this PR I could not add you as a reviewer so please just comment here if you approve these additional changes.

**Comment by grahamegrieve** [comment]
There are plenty of situations where there won't be any possibility for the cds-hooks server to make further requests of the EHR server. the documentation/introspection for a service or maybe the hook defnition should be able to make it clear somewhere that failing to provide the pre-fetch will result in no service being provided

**Comment by isaacvetter** [comment]
Hey @grahamegrieve - what are the situations where it isn't possible for the CDS Hooks service to make follow-up requests to the FHIR server? 
1. Will the "EHR server" know ahead of time that it won't be capable of responding to these requests?
1. I think that the CDS Hooks scope of synchronous, real-time queries will discourage complex network architectures, such as proxies.

**Comment by isaacvetter** [comment]
@kpshek - with the exception of Grahame's above feedback, I think that your modifications are overall an improvement. Looks good.

**Comment by grahamegrieve** [comment]
well, in the case we are working up in Australia, the EHR asks a diagnostic service to comment to the user on the proposed diagnostic service tests. There will be no business arrangement for the diagnostic service to have access back to the EHR (it's technically possible to set it up, but not feasible in practice). So I guess the EHR knows that this is the case ahead of time - by onfiguration, presumably. And i think that the things that cds-hooks can do will make it really compelling to use in spite of complex network topographies, and circumstances where lack of trust is a real impediment to work

**Comment by kpshek** [comment]
@grahamegrieve - Let us know if you'd like any other clarifications or want to discuss your use case further. If so, let's open a new issue for that.

**Pull request merged**
