### PR TITLE
Decision activity proposal

### PR DESCRIPTION
**Pull request by bkaney**
This implements point 3 from https://github.com/cds-hooks/docs/issues/18#issuecomment-282141134

This adds a new concept to the decision return from CDS service to hint at a subsequent action and related resources. This also generalizes the name of "hook catalog" to be called "activity catalog", as it serves as describing actions, of which could be used as web hooks.

### CODE REVIEW

**Comment by jmandel** [comment]
Thanks @bkaney! I think the key contributions here are:

1. Generalizing the activities catalog to work in both directions: an EHR can tell a service "hey, the user is doing this activity", and an app can tell the EHR "hey, here's a good activity for the user to do next". 

2. Updating the decision data model to support this communication back to the EHR

I'm definitely in favor.

I noticed, in the process, that our docs for `decisions.create` are missing something: they specify a list of ids, but what we actually need (and the way our test implementations work) is a list of resources. Does this match your expectations?

**Comment by bkaney** [comment]
> I noticed, in the process, that our docs for decisions.create are missing something: they specify a list of ids, but what we actually need (and the way our test implementations work) is a list of resources. Does this match your expectations?

Yea, they could be resources. However, as we aren't the FHIR server persisting the resource, we'd have to figure out a way to reference them (in the `actions` structure). Perhaps the CDS service would mint an ID for each resource and use #anchor-tag style contained reference?

**Comment by isaacvetter** [comment]
Hey Guys,

This is a really neat idea. I think that a decision returning an EHR activity is great functionality and we should try to make it happen.

1. I'm not sure that a hook and an activity are actually the same thing. For example, take a look at the [proposed hooks](https://github.com/cds-hooks/docs/wiki/Proposed-Hooks), these seem reasonable as hooks, but aren't specific enough to identify an activity.

2. How does the decision define the activity's "parameters". I think that your example specifies a CarePlan as input to a medication-prescribe activity. What does that mean? Is there a medication that should be pre-populated into the EHR's medication-prescribe activity?

Isaac

**Comment by bkaney** [comment]
Hi @isaacvetter --

> I'm not sure that a hook and an activity are actually the same thing. For example, take a look at the proposed hooks, these seem reasonable as hooks, but aren't specific enough to identify an activity.

I see what you mean. I was thinking we avoid having both a "hook catalog" and then another "post hook catalog". Especially after observing the contents both describe what I think of as activities. Instead, there would be a single catalog where the usage context would be as a "hook" or "next action".

> How does the decision define the activity's "parameters". I think that your example specifies a CarePlan as input to a medication-prescribe activity. What does that mean? Is there a medication that should be pre-populated into the EHR's medication-prescribe activity?

I updated the example to be a bit more simplified, including expanding the resources inline. Have a look and see if this addresses your questions.

**Comment by kpshek** [comment]
Given that we've moved decisions out of 1.0, and considering that our specification has changed quite radically (eg, slate -> mkdocs) since this PR was opened, I'm closing this.

When we tackle decisions post 1.0, we can look at this PR for great ideas for possible implementation strategies.

**Pull request closed without merging**
