### PR TITLE
Create Cheat Sheet

### PR DESCRIPTION
**Pull request by dennispatterson**
Following the pattern of FHIR "Cheat Sheets" (e.g. [FHIR R4 pdf](https://fire.ly/wp-content/uploads/2019/01/CHEAT_SHEET_R4_JAN_2019_v1.pdf)), we're introducing a Cheat Sheet for CDS Hooks at DevDays in Redmond this June.  This PR is intended to attain a consensus on its content, as well as facilitating future maintenance.

Initially, I propose that while the raw content lives in this repository, outside coordination with Firely will determine/design/distribute the one-sheet arrangement.  In the future, this repository could use another markdown flavor + css to capture aspects of the unbranded arrangement, as well.

Generic Example: 
[CDS Hooks Cheat Sheet.pdf](https://github.com/cds-hooks/docs/files/3055663/CDS.Hooks.Cheat.Sheet.pdf)

cc: @kpshek @brynrhodes @jmandel @isaacvetter @brettmarquard

### CODE REVIEW

**Comment by brettmarquard** [comment]
@dennispatterson 

Thank you for running with this, I think this is great!

A few quick notes
-	Add link to 1.0 spec (https://cds-hooks.hl7.org/1.0/) 
-	Add link to sandbox (http://sandbox.cds-hooks.org) 
-	Add link to quickstart page (https://cds-hooks.org/quickstart/)
-	Consider splitting into three parts – top part overview picture, links, and items which apply to both CDS client and Server, and then two large boxes underneath for ‘CDS Client’ and ‘CDS services’. CDS clients would have:
o	GET {baseUrl}/cds-services
o	POST {baseUrl}/cds-services/{id}
-	cut down examples a bit – in fact, I think a snipped example plus the tables from the specifications would be best – tables with Required/Recommended/Optional

**Comment by dennispatterson** [comment]
@brettmarquard  Thank you for the feedback! I created a mock-up with your comments applied to see if it's what you have in mind before I rework the markdown.

Note this doesn't include tables, but the markdown would.  You'll see that including abbreviated table content eats up the majority of space so I removed the examples.   My previous mock-up was trying to inject some descriptions into examples and use bold case to communicate required fields.  This one is a bit more like having an abbreviated spec copy.

[CDS Hooks Cheat Sheet spec-based.pdf](https://github.com/cds-hooks/docs/files/3129105/CDS.Hooks.Cheat.Sheet.spec-based.pdf)

**Comment by dennispatterson** [comment]
Held a call with Isaac and Brett.  To try to balance specification contents with examples, I'll try to remove the JWT content and use that space to incorporate example(s) of the request body interactions.

**Comment by dennispatterson** [comment]
Here's the latest mock-up:  [CDS Hooks Cheat Sheet no auth.pdf](https://github.com/cds-hooks/docs/files/3138988/CDS.Hooks.Cheat.Sheet.no.auth.pdf)

Changes:
* removed JWT contents
* reduced font sizes
* use space gained by above changes to add abbreviated examples
* adjustments/corrections to spec content

I'll start working on the associated markdown, but feel free to add a +1 to the proposal or chime in regarding any additional changes you'd like to see.  cc: @brettmarquard  @isaacvetter

**Comment by dennispatterson** [comment]
Thanks for the feedback!  I just pushed a commit with the markdown to match the latest mock-up.  Here's the rendered version - https://github.com/cds-hooks/docs/blob/949b26ab04311faf4e9abbcd18390c89ab4650bf/cheat-sheet/cheat-sheet.md

cc: @brettmarquard @isaacvetter

**Pull request merged**
