### PR TITLE
Add uuid to card

### PR DESCRIPTION
**Pull request by mattvarghese**
Allow cards to have a card identifier.

### CODE REVIEW

**Comment by mattvarghese** [comment]
Chat.fhir.org discussion: https://chat.fhir.org/#narrow/stream/179159-cds-hooks/topic/CDS.20Hooks.20feature.20request

**Comment by mattvarghese** [comment]
CardID is also used in the "Feedback Service" proposal: https://github.com/cds-hooks/docs/wiki/Feedback-endpoint-for-CDS-Hooks-1.1

**Comment by mattvarghese** [comment]
@brynrhodes  I've not created a GitHub issue. Rather, the discussions have been on chat.fhir.org and at the Connectathon. And yes, this is a backwards compatible spec change.

**Comment by mattvarghese** [comment]
@jmandel , @dennispatterson - requesting reviews :)

**Comment by isaacvetter** [comment]
Chatted with @mattvarghese , let's hold off on this PR until the feedback service is written. We're pretty sure that the feedback service is the only reason for adding `card.uuid`.

**Comment by mattvarghese** [comment]
Closing pull request, since UUID was already added to the card.

**Pull request closed without merging**
