### PR TITLE
create problem-list-item-create

### PR DESCRIPTION
**Pull request by isaacvetter**
Propose condition-create hook

### CODE REVIEW

**Comment by isaacvetter** [comment]
Feedback from CDS wg: Should rename this to problem-list-create to distinguish between problist list entries and health concerns, etc.

**Comment by jmandel** [comment]
Love the idea. Naming-wise, why not  call it `condition-create` as you did in the PR text? If you prefer "problem" to "condition," that's fine, but I'm confused by "list" -- since `problem-list-create` sounds like an operation to create a problem list, whereas this is an operation to create one or more *problem*(s) on a list.

**Comment by jmandel** [comment]
(Similar to `appointment-book`.)

**Review by brynrhodes — APPROVED** [review]

**Comment by isaacvetter** [comment]
CDS WG voted to merge this proposed hook into CI build today -- https://confluence.hl7.org/display/CDS/2023-06-14+-+Meeting+Agenda

**Review by vadi2 — APPROVED** [review]

**Pull request merged**
