### PR TITLE
Migrate publication to Github Actions

### PR DESCRIPTION
**Pull request by vadi2**
I've noticed that the Travis build isn't working out all too well - it likely ran out of OSS minutes. Travis is no longer a reliable partner for open-source these days unfortunately, so I've mirrored the publication workflow in Github Actions.

Here's a successful workflow [run](https://github.com/vadi2/docs/runs/2618709822?check_suite_focus=true) and here's [how the results](https://github.com/vadi2/docs/tree/gh-pages) look like. It looks right to me - but if it could get vetted by whomever setup the original workflow, that'd be great.

If we're happy with this then I can delete the Travis config and we can get the builds back!

### CODE REVIEW

**Comment by vadi2** [comment]
Travis is working fine, so I'll close this and but leave the code up should a change is desired in future.

**Comment by isaacvetter** [comment]
@vadi2 !

I wasn't paying enough attention, awesome work and contribution. Below is how I got "travis working fine". It's a temporary fix, unless we want to keep asking travis for OSS credits, as you say. 

I think you're exactly right that we should switch to GH Actions. Lets keep this open and get some review from me, @dennispatterson , @brynrhodes and/or @jmandel .

Isaac

---


From: Erika Kuntar (Support) <support@travis-ci.com> 
Sent: Wednesday, August 4, 2021 5:17 PM
To: Isaac Vetter <isaac@epic.com>
Subject: Travis CI: [31223] - OSS credits? HL7 CDS Hooks

External Mail. Careful of links / attachments. Submit Helpdesk if unsure.

##- Please type your reply above this line -##
from Travis CI has an update for your ticket, #31223. If you'd like to add additional comments, please reply to this email: 
 	Erika Kuntar (Travis CI) 
Aug 4, 2021, 19:16 GMT-3 
Hello Isaac ,

Please accept our sincere apologies for any inconvenience caused due to delays in processing your open-source credit request. 

Open source has always been and always will be at the core of what Travis CI stands for. After reviewing your open source qualifications, I am pleased to notify you that 25k credits were added to your account allowing you to resume running OSS builds. When your credits begin running low again, please reach back out to the Support team.

Credits Consumption Metric
OS.              # CREDITS PER STARTED BUILD MINUTE
Linux.          10
Experimental FreeBSD.         10
Windows.         20
MacOS.         50


Please let us know if you have any questions! 

Thanks and happy building!,
 
Your Friends @Travis-CI

Note: OSS credits may be used solely with respect to open source projects that reside on a public repository. In no event shall OSS credits be used for any commercial project or with respect to any project that resides on a private repository. Travis CI shall determine the amount of all OSS Credit allotments.
--
Erika
Your Friends @Travis CI

Test and Deploy with Confidence.
www.travis-ci.com
—
Travis CI GmbH, Rigaer Str.8, 10247 Berlin, Germany | GF/CEO: Randy Jacops | Contact: contact@travis-ci.org | Amtsgericht Charlottenburg, Berlin, HRB 140133 B | Umsatzsteuer-ID gemäß §27 a Umsatzsteuergesetz: DE282002648


 	Isaac Vetter 
Aug 4, 2021, 18:56 GMT-3 
Hey Erika,
 
Yes, the CDS Hooks project does indeed meet each of the below requirements. 
·        You are a project lead or regular committer (latest commit in the last month)
I am the project lead.
·        Project must be at least 3 months old and is in active development (with regular commits and activity)
Project is active and multiple years old. 
·        Project meets the OSD specification
Yes, I think we do meet the OSD spec.
·        Project must not be an expressly commercial project
·        Project can not provide commercial services or distribute paid versions of the software
We’re expressly non-commercial, have no revenue streams including no commercial services nor paid versions of the software.
 
Appreciate the quick response.
 
Isaac
 
Attachment(s)
~WRD3212.jpg



 	Erika Kuntar (Travis CI) 
Aug 4, 2021, 18:39 GMT-3 
Hello Isaac ,

Thanks for contacting Travis-CI Support! We would love to help. 

We offer an Open Source Subscription for free to non-commercial open-source projects. To qualify for an Open Source subscription, the project must meet the following requirements:
•	You are a project lead or regular committer (latest commit in the last month)
•	Project must be at least 3 months old and is in active development (with regular commits and activity)
•	Project meets the OSD specification
•	Project must not be an expressly commercial project
•	Project can not provide commercial services or distribute paid versions of the software

Does this sound like you and your project? We'd be very happy to support you! 

However, if your project does not match these requirements or you have further questions [1], please feel free to ask!

We look forward to your response if you meet these requirements to proceed with the next steps.

Thank you

[1] https://docs.travis-ci.com/user/billing-faq/
--
Erika
Your Friends @Travis CI

Test and Deploy with Confidence.
www.travis-ci.com
—
Travis CI GmbH, Rigaer Str.8, 10247 Berlin, Germany | GF/CEO: Randy Jacops | Contact: contact@travis-ci.org | Amtsgericht Charlottenburg, Berlin, HRB 140133 B | Umsatzsteuer-ID gemäß §27 a Umsatzsteuergesetz: DE282002648


 	Isaac Vetter 
Aug 4, 2021, 18:19 GMT-3 
Hi Travis-CI Support,
 
My Travis-CI and github account names are: isaacvetter. I’m inquiring about the CDS Hooks project represented as organizations in travis-ci here: https://travis-ci.com/github/cds-hooks and https://github.com/cds-hooks/. 
 
CDS Hooks is an opensource project (see governance, contributor code of conduct) which produces and maintains opensource software as well as an healthcare industry interoperability specification, that’s been adopted by the healthcare specific standard development organization, named HL7. (See: https://cds-hooks.hl7.org/, https://confluence.hl7.org/display/CDS/CDS+Hooks). 
 
We’ve been using travis-ci to run builds of some projects and the interoperability specification website (https://cds-hooks.org) for a number of years under your free plan.  I was wondering if we’d qualify for your OSS credits. We’re a fairly small project with light traffic. I’d expect to rarely exceed ~1000 credits / month, but I’m not sure how calculate accurately.
 
Thanks!
 
Isaac Vetter
 
https://docs.travis-ci.com/user/billing-faq/#what-if-i-am-building-open-source
What if I am building open source? #
Each of the Travis CI Plans contains an amount of special OSS credits per month assigned to run builds only on public repositories. To find out more about it please contact the Travis CI support team. In the email please include:
•	Your account name and your VCS provider (like travis-ci.com/github/[your account name] )
•	How many credits (build minutes) you’d like to request (should your run out of credits again you can repeat the process to request more or to discuss a renewable amount)
 

This email is a service from Travis CI. Delivered by Zendesk 
[YDXK7Q-R4KP]

**Comment by isaacvetter** [comment]
@vadi2, talked over this change with @brynrhodes , it seems clear that GH actions is the right path here. Are you willing to keep owning this switch? I think we'd need to up your permission level on the gh CDS Hooks organization, you should've recently got an email.

**Review by isaacvetter — APPROVED** [review]

**Comment by vadi2** [comment]
Yep I'm good with maintaining it.

**Review by jmandel — APPROVED** [review]

**Review by dennispatterson — APPROVED** [review]

**Comment by vadi2** [comment]
Is this still needed?

I see https://github.com/cds-hooks/docs/actions/runs/4737363627 is already running in github actions. Somehow without a corresponding workflow file - I'm guessing it's using some github built in feature to do the publishing?

**Comment by jmandel** [comment]
I think the workflow you're seeing is being triggered by https://github.com/cds-hooks/docs/commits/gh-pages -- which is to say it's " automatically publishing the content of the GitHub pages branch which has been created and pushed to GitHub by Travis", so it's a pretty trivial automatic publication process but it's not taking Travis out of the loop.

I think it is still worth converting to GitHub actions. It could be short and sweet.

**Comment by vadi2** [comment]
The workflow here still works (here's [a run](https://github.com/vadi2/docs/actions/runs/4816574385/jobs/8576338926) and an updated [gh-pages](https://github.com/vadi2/docs/tree/gh-pages) in my fork), so whoever has the merge permissions go ahead and push the button. Travis would need to be disabled at the same time.

**Comment by jmandel** [comment]
Awesome. I updated your branch to delete the two Travis related files. Will merge this and see what happens 🙂

**Pull request merged**
